// src/utils/services.js
export const PLANS = [
  {
    id: "opportunity",
    title: "Opportunity",
    price: 150,
    billingLabel: "Monthly Value Toward Any Report",
    bullets: [
      "24HR Residential RoofScope",
      "48HR Residential SidingScope",
      "Dedicated Account Manager",
      "Private Label",
      "(1) 3HR Rush ($22 Value)",
      "$11 RoofScopeX",
      "$9 ESX File",
      // placeholders to keep layout balanced
      "-- -- --",
      "-- -- --",
      "-- -- --",
    ],
    badge: null,
    dark: false,
  },
  {
    id: "growth",
    title: "Growth",
    price: 220,
    billingLabel: "Monthly Value Toward Any Report",
    bullets: [
      "5% Report Discount",
      "12HR Residential RoofScope",
      "24HR Residential SidingScope",
      "Dedicated Account Manager",
      "Private Label",
      "(3) 3HR Rush ($66 Value)",
      "(1) ProDocs Users",
      "$3 RoofScope+ Upgrade",
      "Unlimited RoofScopeX Boost",
      "ProData Sheet",
      "$11 RoofScopeX",
      "$9 ESX File",
      "API Integrations",
    ],
    badge: null,
    dark: false,
  },
  {
    id: "advantage",
    title: "Advantage",
    price: 299,
    billingLabel: "Monthly Value Toward Any Report",
    bullets: [
      "7% Report Discount",
      "12HR Residential RoofScope",
      "24HR Residential SidingScope",
      "Dedicated Account Manager",
      "Private Label",
      "(5) 3HR Rush ($110 Value)",
      "(3) ProDocs Users",
      "RoofScope+ Upgrade Included",
      "Unlimited RoofScopeX Boost",
      "ProData Sheet",
      "$11 RoofScopeX",
      "$9 ESX File",
      "API Integrations",
    ],
    badge: "Popular",
    dark: true, // render with dark background to highlight
  },
];
